[package]
name = "opherast-cli"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
dotenvy = "0.15.7"
eyre = "0.6.12"
opherast-core = { path = "../opherast-core" }
opherast = { path = "../../" }