[package]
name = "opherast-framework"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
thiserror = "2.0.12"
sea-orm = "2.0.0-rc.1"
chrono = "0.4.41"
deunicode = "1.6.2"
ulid = "1.2.1"
